---
title: "categroy.data"
author: "Yudi Zhang"
date: "4/8/2018"
output: html_document
---

```{r}
items <- read.csv("/Users/yudi/Downloads/DMC-2018/raw_data/items.csv", sep = "|")
View(items)
prices <- read.csv("/Users/yudi/Downloads/DMC-2018/raw_data/prices.csv", sep = "|")
train <- read.csv("/Users/yudi/Downloads/DMC-2018/raw_data/train.csv", sep = "|")
```

```{r}
library(dplyr)
library(tidyr)
library(lubridate)
library(ggplot2)
library(pander)
library(plotly)
```

##1. Data.Overview
```{r}
#Missing values in subCat
apply(items, 2, function(x) sum(is.na(x)))

#Cat.Overview
table(items$category) %>% pander()
table(items$mainCategory) %>% pander()
table(items$subCategory) %>% pander()

#Only mainCat 1 and 9 have a same cat 37
table(items$category,items$mainCategory) %>% pander()
#mainCat 15 doesn't have subcat
table(items$subCategory,items$category, items$mainCategory) %>% pander()
```




```{r}
train %>% group_by(pid, size) %>% summarise(tot = sum(units)) -> totalsale
inner_join(items, totalsale) -> dat.for.ana

#Sales units by maincat, subcat and categories
dat.for.ana %>% group_by(category, subCategory, mainCategory) %>% summarise(tot.sale=sum(tot)) %>% ggplot(aes(x = as.factor(subCategory),y = tot.sale,col = as.factor(category), shape = as.factor(mainCategory))) + geom_point() + labs(y='Sales Units in the Past Months', x="subCategory") + scale_colour_discrete(name  ="category") + scale_shape_discrete(name  ="mainCategory") 
```


